# KUDOS: https://github.com/jwulf/letsencrypt-nginx-sidecar
version: '2'
services:
    nginx-proxy:
     container_name: nginx
     image: jwilder/nginx-proxy
     ports:
        - "80:7000"
        - "443:7000"
     volumes:
        - "/etc/nginx/vhost.d"
        - "/usr/share/nginx/html"
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "./certs:/etc/nginx/certs"

    letsencrypt-nginx-proxy-companion:
     image: jrcs/letsencrypt-nginx-proxy-companion
     volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
     volumes_from:
        - "nginx-proxy"

networks:
 default:
    external:
        name: letsencrypt